use std::sync::OnceLock;

use crate::rle::{center_cells, parse_rle};

/// Category grouping for a built-in library pattern.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum Category {
    /// Patterns that never change from one generation to the next.
    StillLife,
    /// Patterns that oscillate with a fixed period ≥ 2.
    Oscillator,
    /// Patterns that translate across the grid over time.
    Spaceship,
    /// Patterns that take a large number of generations to stabilise.
    Methuselah,
    /// Patterns that periodically emit spaceships.
    Gun,
    /// Patterns that move while leaving behind debris or other patterns.
    Puffer,
    /// Infinite wick or fuse patterns.
    Wick,
    /// User-saved patterns loaded from `~/.config/newlife/patterns/`.
    Custom,
}

/// A single entry in the built-in pattern library.
///
/// The `rle` field stores a raw RLE string (comments and header optional).
/// Call [`decoded_library`] to get the parsed, centred cell lists.
#[derive(Clone)]
pub struct LibraryEntry {
    /// Human-readable pattern name shown in the browser.
    pub name: &'static str,
    /// Behavioural category used for filtering.
    pub category: Category,
    /// Raw RLE string; decoded lazily via [`decoded_library`].
    pub rle: &'static str,
}

// ── Built-in pattern data (generated by build.rs) ────────────────────────────

// All built-in library patterns.
//
// Generated at compile time by `build.rs`, which scans
// `src/patterns/<category>/*.rle`, derives each entry's display name from the
// file stem, and writes `$OUT_DIR/library_entries.rs`.  Adding a new pattern
// is as simple as dropping a `.rle` file in the right subfolder.
//
// RLE origin does not need to be `(0,0)` — `decoded_library` applies
// `center_cells` after parsing so every returned slice is centred.
include!(concat!(env!("OUT_DIR"), "/library_entries.rs"));

// ── Decoded library (OnceLock) ────────────────────────────────────────────────

/// Decoded library entry: a cloned header plus the centred cell list.
type DecodedEntry = (LibraryEntry, Vec<(i32, i32)>);

static DECODED: OnceLock<Vec<DecodedEntry>> = OnceLock::new();

/// Returns all built-in library entries paired with their decoded, centred cell lists.
///
/// Each RLE string is parsed once via [`parse_rle`] and the result is centred
/// via [`center_cells`].  Entries whose RLE strings fail to parse are silently
/// omitted.  The decoded result is cached for the lifetime of the process.
///
/// # Returns
/// A slice of `(LibraryEntry, cells)` pairs where `cells` contains
/// `(row_offset, col_offset)` pairs centred at `(0, 0)`.
pub fn decoded_library() -> &'static [DecodedEntry] {
    DECODED.get_or_init(|| {
        LIBRARY
            .iter()
            .filter_map(|entry| {
                parse_rle(entry.rle)
                    .ok()
                    .map(|cells| (entry.clone(), center_cells(cells)))
            })
            .collect()
    })
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use crate::grid::Grid;

    /// Asserts that a named library entry loads correctly into a 200×120 grid:
    /// - The entry is found in [`decoded_library`].
    /// - The parsed cell count equals `expected_count`.
    /// - All live cells are within grid bounds.
    /// - The centroid of live cells lies within ±2 cells of the grid centre.
    ///
    /// # Arguments
    /// * `name`           — entry name as in [`LIBRARY`]
    /// * `expected_count` — expected live-cell count after loading
    fn assert_library_entry_valid(name: &str, expected_count: usize) {
        let lib = decoded_library();
        let (_, cells) = lib
            .iter()
            .find(|(e, _)| e.name == name)
            .unwrap_or_else(|| panic!("library entry '{name}' not found"));

        assert_eq!(
            cells.len(),
            expected_count,
            "'{name}': expected {expected_count} cells, got {}",
            cells.len()
        );

        let width = 200usize;
        let height = 120usize;
        let mut g = Grid::new(width, height);
        g.set_cells(cells);

        let live: Vec<(usize, usize)> = (0..height)
            .flat_map(|r| (0..width).map(move |c| (r, c)))
            .filter(|&(r, c)| g.get(r, c))
            .collect();

        assert_eq!(
            live.len(),
            expected_count,
            "'{name}': grid has {} live cells after set_cells, expected {expected_count}",
            live.len()
        );

        for &(r, c) in &live {
            assert!(r < height, "'{name}': row {r} out of bounds");
            assert!(c < width, "'{name}': col {c} out of bounds");
        }

        if !live.is_empty() {
            let sum_r: f64 = live.iter().map(|&(r, _)| r as f64).sum();
            let sum_c: f64 = live.iter().map(|&(_, c)| c as f64).sum();
            let centroid_r = sum_r / live.len() as f64;
            let centroid_c = sum_c / live.len() as f64;
            assert!(
                (centroid_r - height as f64 / 2.0).abs() <= 2.0,
                "'{name}': centroid row {centroid_r:.2} not within ±2 of centre"
            );
            assert!(
                (centroid_c - width as f64 / 2.0).abs() <= 2.0,
                "'{name}': centroid col {centroid_c:.2} not within ±2 of centre"
            );
        }
    }

    #[test]
    fn test_decoded_library_non_empty() {
        assert!(
            !decoded_library().is_empty(),
            "decoded_library() must return at least one entry"
        );
    }

    #[test]
    fn test_all_entries_parse() {
        let lib = decoded_library();
        assert_eq!(
            lib.len(),
            LIBRARY.len(),
            "every LIBRARY entry must parse successfully"
        );
    }

    // ── Still Lifes ──────────────────────────────────────────────────────────
    #[test]
    fn test_library_block() {
        assert_library_entry_valid("Block", 4);
    }
    #[test]
    fn test_library_beehive() {
        assert_library_entry_valid("Beehive", 6);
    }
    #[test]
    fn test_library_loaf() {
        assert_library_entry_valid("Loaf", 7);
    }
    #[test]
    fn test_library_boat() {
        assert_library_entry_valid("Boat", 5);
    }
    #[test]
    fn test_library_tub() {
        assert_library_entry_valid("Tub", 4);
    }
    #[test]
    fn test_library_pond() {
        assert_library_entry_valid("Pond", 8);
    }
    #[test]
    fn test_library_ship() {
        assert_library_entry_valid("Ship", 6);
    }
    #[test]
    fn test_library_long_boat() {
        assert_library_entry_valid("Long Boat", 7);
    }

    // ── Oscillators ──────────────────────────────────────────────────────────
    #[test]
    fn test_library_blinker() {
        assert_library_entry_valid("Blinker", 3);
    }
    #[test]
    fn test_library_toad() {
        assert_library_entry_valid("Toad", 6);
    }
    #[test]
    fn test_library_beacon() {
        assert_library_entry_valid("Beacon", 8);
    }
    #[test]
    fn test_library_pulsar() {
        assert_library_entry_valid("Pulsar", 48);
    }
    #[test]
    fn test_library_pentadecathlon() {
        assert_library_entry_valid("Pentadecathlon", 12);
    }
    #[test]
    fn test_library_figure_eight() {
        assert_library_entry_valid("Figure Eight", 18);
    }
    #[test]
    fn test_library_queen_bee_shuttle() {
        assert_library_entry_valid("Queen Bee Shuttle", 26);
    }
    #[test]
    fn test_library_gosper_glider_gun() {
        assert_library_entry_valid("Gosper Glider Gun", 36);
    }

    // ── Spaceships ───────────────────────────────────────────────────────────
    #[test]
    fn test_library_glider() {
        assert_library_entry_valid("Glider", 5);
    }
    #[test]
    fn test_library_lwss() {
        assert_library_entry_valid("LWSS", 9);
    }
    #[test]
    fn test_library_mwss() {
        assert_library_entry_valid("MWSS", 11);
    }
    #[test]
    fn test_library_hwss() {
        assert_library_entry_valid("HWSS", 13);
    }
    #[test]
    fn test_library_copperhead() {
        assert_library_entry_valid("Copperhead", 28);
    }

    // ── Methuselahs ──────────────────────────────────────────────────────────
    #[test]
    fn test_library_r_pentomino() {
        assert_library_entry_valid("R-Pentomino", 5);
    }
    #[test]
    fn test_library_acorn() {
        assert_library_entry_valid("Acorn", 7);
    }
    #[test]
    fn test_library_diehard() {
        assert_library_entry_valid("Diehard", 7);
    }

    #[test]
    fn test_library_canada_goose() {
        assert_library_entry_valid("Canada Goose", 40);
    }

    /// Verifies the behaviour of every built-in pattern via simulation on a 500x500 grid.
    ///
    /// Still lifes: after 1 step the live-cell set (absolute positions) is unchanged.
    /// Oscillators: after `period` steps the live-cell set (absolute positions) is unchanged.
    /// Spaceships: after `period` steps the normalised shape (each cell expressed relative
    /// to the bounding-box centre) is unchanged, confirming the pattern translated without
    /// dying or exploding.  The per-period displacement (delta_row, delta_col) is printed.
    ///
    /// All patterns are placed with their centred offsets anchored at (200, 200) on a
    /// 500x500 grid — far from all edges so auto-expansion never triggers.
    ///
    /// Note: Gosper Glider Gun is excluded from the oscillator test because it
    /// continuously emits gliders, so the full live-cell set grows each period.
    /// Its cell count is verified separately via `test_library_gosper_glider_gun`.
    #[test]
    fn verify_all_patterns_behaviour() {
        /// Returns the sorted set of live cells for a grid.
        fn live_set(g: &Grid) -> std::collections::BTreeSet<(usize, usize)> {
            (0..g.height)
                .flat_map(|r| (0..g.width).map(move |c| (r, c)))
                .filter(|&(r, c)| g.get(r, c))
                .collect()
        }

        /// Returns the tight bounding box [rmin, cmin, rmax, cmax] of a set of cells,
        /// or None if the set is empty.
        fn bbox(cells: &std::collections::BTreeSet<(usize, usize)>) -> Option<[usize; 4]> {
            if cells.is_empty() {
                return None;
            }
            let mut rmin = usize::MAX;
            let mut cmin = usize::MAX;
            let mut rmax = 0usize;
            let mut cmax = 0usize;
            for &(r, c) in cells {
                rmin = rmin.min(r);
                cmin = cmin.min(c);
                rmax = rmax.max(r);
                cmax = cmax.max(c);
            }
            Some([rmin, cmin, rmax, cmax])
        }

        /// Returns the normalised shape of a live-cell set: each cell expressed as
        /// (row - rmin, col - cmin) so the top-left corner is at (0, 0).
        /// This is translation-invariant and sufficient to check that a spaceship's
        /// shape is preserved across one full period.
        fn normalised_shape(
            cells: &std::collections::BTreeSet<(usize, usize)>,
        ) -> std::collections::BTreeSet<(usize, usize)> {
            match bbox(cells) {
                None => std::collections::BTreeSet::new(),
                Some([rmin, cmin, _, _]) => {
                    cells.iter().map(|&(r, c)| (r - rmin, c - cmin)).collect()
                }
            }
        }

        /// Builds a 500x500 grid with the given centred offsets anchored at (200, 200).
        fn make_grid_at_200(cells_offsets: &[(i32, i32)]) -> Grid {
            let anchor_row: i32 = 200;
            let anchor_col: i32 = 200;
            let mut g = Grid::new(500, 500);
            for &(dr, dc) in cells_offsets {
                let r = anchor_row + dr;
                let c = anchor_col + dc;
                if r >= 0 && r < 500 && c >= 0 && c < 500 {
                    g.set(r as usize, c as usize, true);
                }
            }
            g
        }

        let lib = decoded_library();

        // ── Still lifes ──────────────────────────────────────────────────────────
        let still_life_names = [
            "Block",
            "Beehive",
            "Loaf",
            "Boat",
            "Tub",
            "Pond",
            "Ship",
            "Long Boat",
        ];

        println!("\n=== STILL LIFES ===");
        for &name in &still_life_names {
            let (_, cells) = lib
                .iter()
                .find(|(e, _)| e.name == name)
                .unwrap_or_else(|| panic!("library entry \'{name}\' not found"));

            let mut g = make_grid_at_200(cells);
            let before = live_set(&g);
            let before_count = before.len();
            g.step();
            let after = live_set(&g);
            let after_count = after.len();
            let shape_ok = before == after;

            println!(
                "  {name:<20}  before={before_count:3}  after={after_count:3}  shape_ok={shape_ok}"
            );
            assert!(
                shape_ok,
                "Still life \'{name}\': live-cell set changed after 1 step                  (before={before_count}, after={after_count})"
            );
        }

        // ── Oscillators ──────────────────────────────────────────────────────────
        // Gosper Glider Gun is excluded: it emits gliders each period so the total
        // live-cell set always grows. Its structure is verified in test_library_gosper_glider_gun.
        let oscillators: &[(&str, usize)] = &[
            ("Blinker", 2),
            ("Toad", 2),
            ("Beacon", 2),
            ("Pulsar", 3),
            ("Pentadecathlon", 15),
            ("Figure Eight", 8),
            ("Queen Bee Shuttle", 30),
        ];

        println!("\n=== OSCILLATORS ===");
        for &(name, period) in oscillators {
            let (_, cells) = lib
                .iter()
                .find(|(e, _)| e.name == name)
                .unwrap_or_else(|| panic!("library entry \'{name}\' not found"));

            let mut g = make_grid_at_200(cells);
            let before = live_set(&g);
            let before_count = before.len();
            for _ in 0..period {
                g.step();
            }
            let after = live_set(&g);
            let after_count = after.len();
            let shape_ok = before == after;

            println!(
                "  {name:<25}  period={period:2}  before={before_count:3}  after={after_count:3}  shape_ok={shape_ok}"
            );
            assert!(
                shape_ok,
                "Oscillator \'{name}\' (period={period}): live-cell set changed after                  {period} steps (before={before_count}, after={after_count})"
            );
        }

        // ── Spaceships ───────────────────────────────────────────────────────────
        // (name, period)
        let spaceships: &[(&str, usize)] = &[
            ("Glider", 4),
            ("LWSS", 4),
            ("MWSS", 4),
            ("HWSS", 4),
            ("Copperhead", 10),
            ("Canada Goose", 4),
        ];

        println!("\n=== SPACESHIPS ===");
        for &(name, period) in spaceships {
            let (_, cells) = lib
                .iter()
                .find(|(e, _)| e.name == name)
                .unwrap_or_else(|| panic!("library entry \'{name}\' not found"));

            let mut g = make_grid_at_200(cells);
            let before = live_set(&g);
            let before_count = before.len();
            let shape_before = normalised_shape(&before);

            // Capture bounding-box centre before stepping
            let bbox_before = bbox(&before);

            for _ in 0..period {
                g.step();
            }
            let after = live_set(&g);
            let after_count = after.len();
            let shape_after = normalised_shape(&after);
            let shape_ok = shape_before == shape_after;

            // Compute displacement as change in bounding-box top-left corner
            let (delta_row, delta_col) = match (bbox_before, bbox(&after)) {
                (
                    Some([rmin_b, cmin_b, rmax_b, cmax_b]),
                    Some([rmin_a, cmin_a, rmax_a, cmax_a]),
                ) => {
                    let centre_row_before = rmin_b as i64 + rmax_b as i64;
                    let centre_col_before = cmin_b as i64 + cmax_b as i64;
                    let centre_row_after = rmin_a as i64 + rmax_a as i64;
                    let centre_col_after = cmin_a as i64 + cmax_a as i64;
                    (
                        (centre_row_after - centre_row_before) / 2,
                        (centre_col_after - centre_col_before) / 2,
                    )
                }
                _ => (0, 0),
            };

            println!(
                "  {name:<20}  period={period:2}  before={before_count:3}  after={after_count:3}                   shape_ok={shape_ok}  displacement=({delta_row},{delta_col})"
            );
            assert!(
                shape_ok,
                "Spaceship \'{name}\' (period={period}): normalised shape changed after                  {period} steps (before={before_count}, after={after_count})"
            );
            assert_eq!(
                before_count, after_count,
                "Spaceship \'{name}\': cell count changed                  (before={before_count}, after={after_count})"
            );
        }

        println!("\n=== ALL PATTERNS OK ===");
    }
}
